### PR TITLE
update Power part

### PR DESCRIPTION
**Pull request by HKhademian**
in this commits:
* add `pow` function for all Number types returning their same number type
* add `Number.pow` function that accepts all type of numbers and return `Double`
* makes `pow` function `infix` so that functions can use `1 pow 2` or `3.pow(4)`
* `pow` now accepts all types of `Number`s like `3.5 pow 2` or `3f pow 8` or `8.pow(6L)`

### CODE REVIEW

**Comment by MarcinMoskala** [comment]
As code coverage tool shouts - these methods should be tested.

**Comment by HKhademian** [comment]
it errors because in my commit says `Int.power(Int):Int` is removed but I add `Int.power(Number):Int` that accepts all the older one with some extra. even their function code is absolutely the same.

**Comment by MarcinMoskala** [comment]
It also shows that test coverage dropped from 100% to 92%

**Comment by LarsArtmann** [comment]
See pull request #5

**Pull request closed without merging**
